# Generated by Django 4.0.5 on 2022-06-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Book',
        ),
    ]
