# Generated by Django 4.0.5 on 2022-06-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medx', '0004_rename_book_topic_rename_book_entry_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='book',
        ),
    ]
